#pragma once

#import <libfreenect2/allocator.h>
#import <libfreenect2/async_packet_processor.h>
#import <libfreenect2/color_settings.h>
#import <libfreenect2/command.h>
#import <libfreenect2/command_transaction.h>
#import <libfreenect2/config.h>
#import <libfreenect2/depth_packet_processor.h>
#import <libfreenect2/depth_packet_stream_parser.h>
#import <libfreenect2/event_loop.h>
#import <libfreenect2/export.h>
#import <libfreenect2/frame_listener.hpp>
#import <libfreenect2/frame_listener_impl.h>
#import <libfreenect2/led_settings.h>
#import <libfreenect2/libfreenect2.h>
#import <libfreenect2/libfreenect2.hpp>
#import <libfreenect2/logger.h>
#import <libfreenect2/logging.h>
#import <libfreenect2/packet_pipeline.h>
#import <libfreenect2/packet_processor.h>
#import <libfreenect2/registration.h>
#import <libfreenect2/resource.h>
#import <libfreenect2/resources.inc.h>
#import <libfreenect2/response.h>
#import <libfreenect2/rgb_packet_processor.h>
#import <libfreenect2/rgb_packet_stream_parser.h>
#import <libfreenect2/threading.h>
#import <libfreenect2/transfer_pool.h>
#import <libfreenect2/usb_control.h>
